### ISSUE TITLE
No reply with 0.8.17

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.icndb#1]
Could be my pronunciation but v1.0.1 doesn't seem to work in homey 0.8.17 ?

**Comment by WeeJeWel** [comment]
It should work. 'Tell me a Chuck Norris joke'.

Please try to debug your speech, e.g. by sending a push notification to your phone when Homey heard something.

**Comment by bvdbos** [comment]
This  works "Chuck Norris grap"
